In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

arr4 = np.where(arr == 4)

print(arr4)

for i in arr4:
    print(arr[i])

(array([3, 5, 6], dtype=int64),)
[4 4 4]


In [3]:
x = np.where(arr % 2 == 0)

print(x)

(array([1, 3, 5, 6], dtype=int64),)


In [4]:
arr = np.array([3, 2, 0, 1])

accending = np.sort(arr)

print(accending)

[0 1 2 3]


In [5]:
decinding = accending[::-1] # when the step is -1 thats mean it is reversed

print(decinding)

[3 2 1 0]


In [6]:
arr = np.array(['banana', 'cherry', 'apple'])

new = np.sort(arr)

print(new)

['apple' 'banana' 'cherry']


In [7]:
arr = np.array([41, 42, 43, 44])

filtter_arr = [False, True, False, True]
new = arr[filtter_arr]

print(new)

[42 44]


In [15]:
arr = np.array([41, 42, 43, 44])

filtter_arr = []

for i in arr:
    if i > 42:
        filtter_arr.append(True)
    else:
        filtter_arr.append(False)

newarr = arr[filtter_arr]

print(newarr)

new = [i for i in arr if i > 42]
print(new)

new2 = arr[arr > 42]
print(new2)

arr

[43 44]
[43, 44]
[43 44]


array([41, 42, 43, 44])

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filtter_arr = arr % 2 == 0

newarr = arr[filtter_arr]

print(newarr)
print(filtter_arr)

[2 4 6]
[False  True False  True False  True False]


In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr.shape

(2, 4)

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new = arr.reshape(3,4)

print(new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
flat = new.reshape(-1) # -1 in reshape function flats the array

print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
