In [1]:
import numpy as np

In [6]:
a1 = np.array(1)
a2 = np.array([1,2,3,4])
a3 = np.array([[1,2,3,4],[5,6,7,8]])
a4 = np.array([
    [[1,2,3,4],
    [5,6,7,8]],
    [[9,10,11,12],
    [13,14,15,16]]
])

print(a1)
print(a2)
print(a3)
print(a4)

1
[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [10]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a4.ndim)

0
1
2
3


In [11]:
print(type(a1))

<class 'numpy.ndarray'>


In [12]:
print(a2[2])

3


In [15]:
print(a3[1,2])

7


In [18]:
print(a4[0])
print(a4[0,1])
print(a4[0,1,-1])

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8]
8


In [19]:
print(a2[1:4])

[2 3 4]


In [21]:
print(a2[0::2])

[1 3]


In [22]:
for x in a3:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [23]:
for x in a3:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8


In [26]:
for x in np.nditer(a3):
    print(x)

1
2
3
4
5
6
7
8
