In [1]:
import numpy as np

In [22]:
arr = np.array([[1,2,3],[4,5,6]])

In [5]:
arr.shape

(2, 3)

In [6]:
arr.ndim

2

In [11]:
arr.size

6

In [12]:
arr.dtype

dtype('int32')

In [20]:
arr.nbytes

24

In [21]:
arr.itemsize

4

In [23]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [30]:
a = np.array([1,2,3,4,5])

In [31]:
a + 1

array([2, 3, 4, 5, 6])

In [32]:
a * 2

array([ 2,  4,  6,  8, 10])

In [33]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [34]:
np.power(a , 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [35]:
np.sum(a)

15

In [37]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [38]:
arr.sum(axis=0)

array([4, 6])

In [39]:
arr.sum(axis=1)

array([3, 7])

In [41]:
arr1 = np.array([
    [1,1],
    [2,1]])
arr2 = np.array([
    [1,1],
    [1,2]])

arr1 == arr2

array([[ True,  True],
       [False, False]])

In [42]:
np.array_equal(arr1,arr2)

False